/* eslint-disable */
// GENERATED by scripts/gen-types.mjs from `pagelamp schema` — DO NOT EDIT.
// Source of truth: crates/pagelamp-app/src/lib.rs, crates/pagelamp-core/src/{model,views}.rs

/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "ActivityKind".
 */
export type ActivityKind = "sync" | "download";
/**
 * Which backend a choice or an acknowledgement is about.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "BackendRef".
 */
export type BackendRef =
  | {
      kind: "codex";
    }
  | {
      kind: "claude_code";
    }
  | {
      kind: "provider";
      provider_id: string;
    };
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CostKind".
 */
export type CostKind =
  "free_on_device" | "api_billing" | "plan_credits" | "cloud_via_local" | "self_hosted";
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "RetentionFact".
 */
export type RetentionFact =
  | {
      kind: "not_stored";
    }
  | {
      days: number;
      kind: "stored_days";
    }
  | {
      kind: "provider_terms";
    }
  | {
      kind: "on_device";
    };
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "SentData".
 */
export type SentData = "structure" | "material_text";
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "TrainingFact".
 */
export type TrainingFact =
  | {
      kind: "no_training";
    }
  | {
      how_to_turn_off_url?: string | null;
      kind: "may_train";
    }
  | {
      kind: "may_train_free_tier";
    }
  | {
      kind: "unknown";
    };
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "BackendKind".
 */
export type BackendKind = "api_key" | "local" | "codex" | "claude_code";
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "BackendProblem".
 */
export type BackendProblem =
  "key_missing" | "server_not_running" | "model_missing" | "disclosure_changed";
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "BackendState".
 */
export type BackendState = ("ready" | "needs_setup" | "unavailable") | "needs_disclosure";
/**
 * A feature that runs a model.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "AiFeature".
 */
export type AiFeature = "study_plan" | "weekly_explanation" | "weekly_note" | "course_calendar";
/**
 * Whether an AI app may read a course's material TEXT over MCP (docs/ARCHITECTURE.md §3
 * rule 8). Computed from `Course.ai_policy` and `Course.ai_access`, never stored.
 * Structure (titles, kinds, dates, weeks, URLs, counts), deadlines and study plans are
 * always available; only material text is withheld.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "AiMaterialsState".
 */
export type AiMaterialsState = "readable" | "turned_off" | "withheld_by_policy";
/**
 * How the student is allowed to use generative AI in a course. Defaults to `Unknown`,
 * which consumers must treat like `LearningAid` for explanations but must never treat as
 * permission to produce graded work (UofT default: GenAI not permitted unless allowed).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "AiPolicy".
 */
export type AiPolicy =
  "unknown" | "prohibited" | "learning_aid" | "allowed_with_citation" | "unrestricted";
/**
 * How hard the model should think. Mapped per wire: "lowest" is the cheapest setting the
 * model allows (`none` / `minimal`, or `low` where thinking can't be turned off).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "Effort".
 */
export type Effort = "lowest" | "low" | "medium" | "high";
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "ProviderWire".
 */
export type ProviderWire =
  "openai_responses" | "openai_chat" | "anthropic_messages" | "ollama_native";
/**
 * Why a model call was refused before anything was sent.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "BlockReason".
 */
export type BlockReason =
  | (
      | "course_hidden"
      | "no_readable_materials"
      | "disclosure_not_acknowledged"
      | "no_model_chosen"
      | "backend_disabled_in_this_build"
    )
  | "course_policy_prohibited"
  | "course_ai_turned_off"
  | "material_sharing_not_allowed"
  | "coding_plan_key"
  | "budget_reached"
  | "price_unknown_not_acknowledged"
  | "weekly_run_cap_reached";
/**
 * What kind of failure happened; UIs branch on this, never on `message`.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "AppErrorKind".
 */
export type AppErrorKind =
  | "auth"
  | "network"
  | "invalid"
  | "not_found"
  | "ambiguous"
  | "busy"
  | "schema_too_new"
  | "schema_too_old"
  | "blocked"
  | "model"
  | "cancelled"
  | "internal";
/**
 * Why a model call failed (the facade's `SourceErrorKind` for models).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "ModelErrorKind".
 */
export type ModelErrorKind =
  | ("model_not_found" | "context_too_long" | "network" | "timeout")
  | "not_signed_in"
  | "auth_rejected"
  | "billing_or_quota"
  | "usage_limit"
  | "rate_limited"
  | "overloaded"
  | "invalid_request"
  | "refused"
  | "content_filtered"
  | "bad_output"
  | "runtime_missing"
  | "runtime_verify_failed"
  | "runtime_outdated"
  | "unsupported";
/**
 * Where course data comes from.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "SourceKind".
 */
export type SourceKind = "canvas" | "folder" | "ical";
/**
 * Why a source failed to sync. Persisted as `sources.last_error_kind`.
 *
 * Classification: Canvas 401 / invalid token and feed-URL 401/403 → `AuthExpiredOrRevoked`;
 * DNS/TLS/timeout/connection refused → `Network`; missing folder, feed 404 or Canvas host 404
 * → `NotFound`; Canvas throttling still failing after all retries → `RateLimited`.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "SourceErrorKind".
 */
export type SourceErrorKind =
  "auth_expired_or_revoked" | "network" | "not_found" | "rate_limited" | "other";
/**
 * Progress of `read_course_calendars`: one course after another, each with its `GenEvent`s.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CalendarBatchEvent".
 */
export type CalendarBatchEvent =
  | {
      course_id: string;
      /**
       * 0-based.
       */
      index: number;
      total: number;
      type: "course_started";
    }
  | {
      course_id: string;
      event: GenEvent;
      type: "gen";
    }
  | {
      outcome: CalendarRunOutcome;
      type: "course_finished";
    };
/**
 * What a generation reports while it runs.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "GenEvent".
 */
export type GenEvent =
  | {
      backend_label: string;
      generation_id: string;
      model: string;
      on_device: boolean;
      type: "started";
    }
  | {
      stage: GenStage;
      type: "stage";
    }
  | {
      text: string;
      type: "text_delta";
    }
  | {
      code: GenNoticeCode;
      type: "notice";
    }
  | {
      type: "usage";
      usage: TokenUsage;
    }
  | {
      ok: boolean;
      type: "finished";
    };
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "GenStage".
 */
export type GenStage =
  "building_context" | "waiting_for_model" | "validating" | "repairing" | "scheduling";
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "GenNoticeCode".
 */
export type GenNoticeCode =
  | (
      | "context_trimmed"
      | "thinking_always_on"
      | "json_fallback"
      | "courses_structure_only"
      | "materials_left_out"
      | "api_key_billing"
    )
  | "material_sharing_reminder";
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "MaterialKind".
 */
export type MaterialKind = ("announcement" | "syllabus") | "file" | "page" | "external_link";
/**
 * Why a candidate is not read.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CandidateLeftOut".
 */
export type CandidateLeftOut = "no_text" | "scanned" | "over_budget" | "excluded_by_student";
/**
 * Why a material is a candidate.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CandidateReason".
 */
export type CandidateReason =
  | "announcement"
  | "syllabus"
  | "linked_from_syllabus"
  | "title_outline"
  | "title_schedule"
  | "title_info"
  | "front_page"
  | "start_module"
  | "named_in_course_toml"
  | "student_added";
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "BreakKind".
 */
export type BreakKind = "reading_week" | "holiday" | "winter_break" | "other";
/**
 * What accepting would change (UIs translate the code; params follow the evidence-param
 * conventions, plus `from_phase` / `to_phase` holding `CoursePhase` values).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "ChangeCode".
 */
export type ChangeCode =
  | "new_calendar"
  | "first_class_moved"
  | "last_class_moved"
  | "break_added"
  | "break_removed"
  | "exams_end_moved"
  | "week_today_changes"
  | "phase_changes";
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "ConflictCode".
 */
export type ConflictCode =
  | (
      | "disagrees_with_lms_dates"
      | "disagrees_with_class_event"
      | "differs_from_institution_calendar"
    )
  | "syllabus_from_another_year"
  | "inconsistent"
  | "disagrees_with_notes";
/**
 * What a proposed date is.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "DateKind".
 */
export type DateKind =
  ("first_class" | "last_class" | "exam_period" | "final_exam") | "break_span" | "week_start";
/**
 * Why a claim or row was dropped.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "DropReason".
 */
export type DropReason =
  | "unknown_source"
  | "unsupported_quote"
  | "date_not_in_quote"
  | "ambiguous_year"
  | "outside_frame"
  | "inconsistent"
  | "table_dropped";
/**
 * Where a student-confirmed calendar came from.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CalendarOrigin".
 */
export type CalendarOrigin = ("scan" | "ai" | "ai_app" | "restored") | "user" | "legacy";
/**
 * Where a course is in its term (design §6.6). Every exclusion rule uses the lifecycle
 * (`CourseLifecycle`), never the phase: the phase only drives labels and the week.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CoursePhase".
 */
export type CoursePhase =
  "ended" | "not_started" | "teaching" | "break" | "exam_period" | "unknown";
/**
 * How a usage row's cost is known (the UIs label it: "≈ $x", "Free", "price unknown", "your
 * plan").
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CostBasis".
 */
export type CostBasis = "priced" | "free_on_device" | "unpriced" | "plan";
/**
 * Whether the course has a calendar the student accepted (from alpha.2; always `None` in
 * alpha.1).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CalendarStatus".
 */
export type CalendarStatus = ("proposed" | "accepted" | "accepted_stale") | "none";
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "Confidence".
 */
export type Confidence = "high" | "medium" | "low";
/**
 * How course lists group courses (the same in Tauri, Swift and the CLI).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CourseGroup".
 */
export type CourseGroup = "current" | "upcoming" | "past";
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "LifecycleState".
 */
export type LifecycleState =
  ("upcoming" | "current" | "ended" | "unknown") | "finishing" | "inactive";
/**
 * Why a file that is recorded `NotDownloaded` cannot be downloaded by asking again.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "DownloadBlock".
 */
export type DownloadBlock = "locked" | "too_large";
/**
 * Why a material's text can't be read (`MaterialView::text_problem`). It is worked out when
 * the view is built, from `text_status`, the chunk count, `text_error_kind` and the
 * extractor's message, so it also covers failures that earlier versions recorded.
 * `text_error` keeps the full message for the CLI, logs and MCP.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "TextProblem".
 */
export type TextProblem =
  | "no_text"
  | "too_large"
  | "password_protected"
  | "malformed"
  | "timed_out"
  | "cpu_limit"
  | "memory_limit"
  | "crashed"
  | "bad_output"
  | "spawn_failed"
  | "protocol_mismatch"
  | "other";
/**
 * Whether we have searchable text for a material.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "TextStatus".
 */
export type TextStatus = "pending" | "ok" | "unsupported" | "not_downloaded" | "error";
/**
 * Which dates set week 1 (design §6.4; the first available one wins).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "TermAnchorSource".
 */
export type TermAnchorSource =
  | "student_confirmed"
  | "lms_course_dates"
  | "lms_term"
  | "folder_config"
  | "institution_calendar"
  | "published_week_labels"
  | "none";
/**
 * Why dates were not used (design §6.3).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "RejectReason".
 */
export type RejectReason =
  | ("starts_after_end" | "conflicts_with_stronger_source")
  | "longer_than_teaching_term"
  | "shorter_than_teaching_term"
  | "starts_long_before_activity"
  | "starts_before_session_window"
  | "end_outside_session_window";
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "EventKind".
 */
export type EventKind =
  ("assignment_due" | "quiz_due" | "exam" | "other") | "class_event" | "planner_item";
/**
 * Which kind of process writes the log (selects the file name).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "ProcessKind".
 */
export type ProcessKind = "app" | "mcp";
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "LocalServerKind".
 */
export type LocalServerKind = "ollama" | "lm_studio";
/**
 * Whether the extraction worker (`pagelamp extract-worker`, v0.3 M0.5) works.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "ExtractWorkerStatus".
 */
export type ExtractWorkerStatus =
  "ok" | "not_set" | "spawn_failed" | "protocol_mismatch" | "failed";
/**
 * Why the extraction worker (`pagelamp extract-worker`, v0.3 M0.5) could not read a file:
 * `materials.text_error_kind`, next to `text_status = error`. Same names as
 * `pagelamp_extract::worker::WorkerFailure`.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "TextErrorKind".
 */
export type TextErrorKind =
  | "timed_out"
  | "cpu_limit"
  | "memory_limit"
  | "crashed"
  | "bad_output"
  | "spawn_failed"
  | "protocol_mismatch";
/**
 * What an estimate is for.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "EstimateRequest".
 */
export type EstimateRequest =
  | {
      /**
       * Course ids or codes (empty: the default set).
       */
      courses: string[];
      feature: "study_plan";
      horizon_days?: number | null;
    }
  | {
      course: string;
      feature: "weekly_explanation";
      week?: number | null;
    }
  | {
      feature: "weekly_note";
    }
  | {
      courses: string[];
      feature: "course_calendar";
    };
/**
 * Every `EvidenceItem.code`. Exported in the facade schema so UIs can check their
 * translations are complete; the item itself carries the code as a string.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "EvidenceCode".
 */
export type EvidenceCode =
  | "student_dates"
  | "legacy_dates"
  | "student_end_used"
  | "lms_course_dates"
  | "lms_term_dates"
  | "folder_dates"
  | "institution_calendar"
  | "week_labels_fit"
  | "no_course_dates"
  | "term_looks_like_enrollment_window"
  | "dates_not_used"
  | "end_not_used"
  | "dates_agree"
  | "dates_may_be_wrong"
  | "session_window"
  | "institution_calendar_missing"
  | "week_from_dates"
  | "week_from_module_unlock"
  | "week_from_recent_materials"
  | "week_from_latest_material"
  | "signal_agrees"
  | "signal_disagrees"
  | "modules_released_together"
  | "unlock_too_old"
  | "unlock_without_week"
  | "bulk_publish"
  | "notes_ahead"
  | "calendar_disagrees_with_notes"
  | "numbering_offset"
  | "breaks_unknown"
  | "no_week_signal"
  | "starts_on"
  | "in_break"
  | "no_class_today"
  | "exam_period"
  | "exam_period_estimated"
  | "ended_on"
  | "start_too_old"
  | "kept_current"
  | "lms_concluded"
  | "lms_completed"
  | "no_longer_listed"
  | "exams_over"
  | "course_end_passed"
  | "dates_ended"
  | "term_end_passed"
  | "session_ended"
  | "quiet_since"
  | "no_activity"
  | "recent_activity"
  | "next_event"
  | "session_starts"
  | "no_dates_inactive"
  | "may_have_ended"
  | "removal_snoozed"
  | "removal_kept";
/**
 * Which week signal an evidence item talks about (`signal` parameter).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "EvidenceSignal".
 */
export type EvidenceSignal = ("module_unlock" | "recent_materials" | "latest_material") | "dates";
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "LeftOutReason".
 */
export type LeftOutReason = ("external_link" | "no_text") | "looks_like_assessment" | "over_budget";
/**
 * The student's answer to "May this course's materials be shared with an AI service?"
 * (design §4.1, question (b); `courses.material_sharing`, schema v4). Only `not_allowed` stops
 * material text from going to a cloud backend (owner decision D37, option 2).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "MaterialSharing".
 */
export type MaterialSharing = "unanswered" | "allowed" | "not_sure" | "not_allowed";
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "McpClient".
 */
export type McpClient = "claude_desktop" | "claude_code" | "codex" | "generic";
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "InstallKind".
 */
export type InstallKind = "json_snippet" | "shell_command" | "toml_snippet";
/**
 * A place the `pagelamp` binary runs from that won't exist (or move) later, so an AI app
 * configured with that path loses the server.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "TemporaryLocation".
 */
export type TemporaryLocation = "disk_image" | "translocated" | "appimage";
/**
 * Stable codes for `McpClientConfig.notes` (one code per note).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "McpNoteCode".
 */
export type McpNoteCode =
  | "works_on_all_claude_plans"
  | "admins_may_disable_extensions"
  | "needs_paid_claude_plan"
  | "codex_config_shared_with_chatgpt_desktop"
  | "codex_plus_and_edu_documented"
  | "free_go_undocumented"
  | "restart_client_after_change"
  | "quit_before_editing"
  | "custom_data_dir"
  | "generic_stdio_client"
  | "run_from_temporary_location";
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "StructuredOutputTier".
 */
export type StructuredOutputTier = "native_schema" | "json_object" | "prompt_only";
/**
 * What a later sync can't bring back once a course is purged (§8.3).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "LostAfterPurge".
 */
export type LostAfterPurge =
  "old_announcements" | "locked_files" | "whole_course" | "redownload_counts_as_viewing";
/**
 * Why a course was removed (display only).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "RemovalReason".
 */
export type RemovalReason = "ended" | "inactive" | "not_mine" | "other";
/**
 * Where a removed course is in the two stages.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "TombstoneState".
 */
export type TombstoneState = "pending" | "purged" | "restoring";
/**
 * Why a purged course didn't come back.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "RestoreFailure".
 */
export type RestoreFailure = ("offline" | "other") | "not_listed" | "access_restricted";
/**
 * The answer to a removal suggestion.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "SnoozeKind".
 */
export type SnoozeKind = "not_now" | "keep";
/**
 * A topic of the one-time What's new sheet shown after an update.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "WhatsNewTopic".
 */
export type WhatsNewTopic = "update_check" | "course_weeks" | "course_removal";
/**
 * Progress stream of a sync run (desktop forwards these through a `tauri::ipc::Channel`).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "SyncEvent".
 */
export type SyncEvent =
  | {
      label: string;
      source_id: string;
      type: "source_started";
    }
  | {
      /**
       * The course the step is about (its code, else its name).
       */
      course?: string | null;
      current?: number | null;
      /**
       * English, for the CLI and logs; the UIs translate `stage` when it is set.
       */
      message: string;
      source_id: string;
      stage?: SyncStage | null;
      total?: number | null;
      type: "progress";
    }
  | {
      message: string;
      source_id: string;
      type: "warning";
    }
  | {
      error?: string | null;
      error_kind?: SourceErrorKind | null;
      ok: boolean;
      source_id: string;
      type: "source_finished";
    };
/**
 * What a sync step is doing, as a code the UIs translate (with `course`, `current` and `total`
 * filled in); the step's English `message` stays for the CLI, logs and older clients.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "SyncStage".
 */
export type SyncStage =
  | "checking_access"
  | "listing_courses"
  | "reading_course"
  | "downloading_files"
  | "scanning_files"
  | "indexing_files"
  | "downloading_feed"
  | "saving_events";
/**
 * Origin of a course's effective term dates.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "TermSource".
 */
export type TermSource = "user" | "synced" | "none";
/**
 * Where updates come from.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "UpdateChannel".
 */
export type UpdateChannel = "stable" | "beta";
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "UpdateCheckOutcome".
 */
export type UpdateCheckOutcome =
  | {
      kind: "up_to_date";
    }
  | {
      kind: "available";
      version: string;
    }
  | {
      code: string;
      kind: "error";
    };
/**
 * Why `WeekMaterials.note` is set.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "WeekNoteKind".
 */
export type WeekNoteKind =
  "current_week_unknown" | "outside_term" | "no_materials_this_week" | "exam_period" | "break";

/**
 * Container whose only purpose is to pull every facade type into one schema document
 * (`$defs`), so json-schema-to-typescript emits one TS file with all of them.
 */
export interface PageLampAppTypes {
  activity: Activity;
  activity_item: ActivityItem;
  activity_kind: ActivityKind;
  ai_backend_status: AiBackendStatus;
  ai_feature: AiFeature;
  ai_materials_state: AiMaterialsState;
  ai_policy: AiPolicy;
  ai_status: AiStatus;
  app_error: AppError;
  app_status: AppStatus;
  backend_kind: BackendKind;
  backend_problem: BackendProblem;
  backend_ref: BackendRef;
  backend_state: BackendState;
  block_reason: BlockReason;
  budget_status: BudgetStatus;
  calendar_batch_event: CalendarBatchEvent;
  calendar_candidate: CalendarCandidate;
  calendar_proposal: CalendarProposal;
  calendar_run_outcome: CalendarRunOutcome;
  cost_basis: CostBasis;
  cost_estimate: CostEstimate;
  cost_kind: CostKind;
  course_calendar_view: CourseCalendarView;
  course_dates_input: CourseDatesInput;
  course_overview: CourseOverview;
  course_summary: CourseSummary;
  course_sync_summary: CourseSyncSummary;
  course_timeline: CourseTimeline;
  crash_report: CrashReport;
  deadline: Deadline;
  disclosure_facts: DisclosureFacts;
  doctor_report: DoctorReport;
  effort: Effort;
  estimate_request: EstimateRequest;
  evidence_code: EvidenceCode;
  evidence_signal: EvidenceSignal;
  extract_worker_check: ExtractWorkerCheck;
  extract_worker_status: ExtractWorkerStatus;
  feature_routing: FeatureRouting;
  gen_event: GenEvent;
  gen_notice_code: GenNoticeCode;
  gen_stage: GenStage;
  generation_meta: GenerationMeta;
  lifecycle_summary: LifecycleSummary;
  local_server: LocalServer;
  local_server_kind: LocalServerKind;
  material_sharing: MaterialSharing;
  mcp_client_config: McpClientConfig;
  model_choice: ModelChoice;
  model_error_kind: ModelErrorKind;
  model_info: ModelInfo;
  model_provider_record: ModelProviderRecord;
  probe_report: ProbeReport;
  process_kind: ProcessKind;
  provider_preset: ProviderPreset;
  provider_wire: ProviderWire;
  purge_report: PurgeReport;
  read_calendar_options: ReadCalendarOptions;
  recipient: Recipient;
  removal_preview: RemovalPreview;
  removal_report: RemovalReport;
  remove_ai_data_report: RemoveAiDataReport;
  remove_options: RemoveOptions;
  restore_outcome: RestoreOutcome;
  retention_fact: RetentionFact;
  search_hit: SearchHit;
  sent_data: SentData;
  snooze_kind: SnoozeKind;
  source_error_kind: SourceErrorKind;
  source_record: SourceRecord;
  source_sync_result: SourceSyncResult;
  startup_tasks: StartupTasks;
  stored_study_plan: StoredStudyPlan;
  structured_output_tier: StructuredOutputTier;
  syllabus_offer: SyllabusOffer;
  sync_event: SyncEvent;
  sync_request: SyncRequest;
  sync_summary: SyncSummary;
  term_source: TermSource;
  text_error_kind: TextErrorKind;
  token_usage: TokenUsage;
  training_fact: TrainingFact;
  unreadable_files: UnreadableFiles;
  update_channel: UpdateChannel;
  update_check_outcome: UpdateCheckOutcome;
  update_check_record: UpdateCheckRecord;
  update_prefs: UpdatePrefs;
  usage_row: UsageRow;
  usage_summary: UsageSummary;
  week_materials: WeekMaterials;
  whats_new: WhatsNew;
  whats_new_topic: WhatsNewTopic;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "Activity".
 */
export interface Activity {
  /**
   * Work this app is doing, oldest first.
   */
  items: ActivityItem[];
  /**
   * Another process (the CLI, another window) is syncing: `sync.lock` is held, but not by
   * this app.
   */
  other_process_syncing: boolean;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "ActivityItem".
 */
export interface ActivityItem {
  kind: ActivityKind;
  /**
   * The one source it works on; `None` for `sync_all`.
   */
  source_id?: string | null;
  started_at: string;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "AiBackendStatus".
 */
export interface AiBackendStatus {
  backend: BackendRef;
  disclosure: DisclosureFacts;
  /**
   * The disclosure version the student acknowledged, if any.
   */
  disclosure_acknowledged?: number | null;
  kind: BackendKind;
  label: string;
  problems: BackendProblem[];
  state: BackendState;
}
/**
 * What a backend is told and what happens to it (Canvas §2E items): codes and plain values the
 * UIs render. The UIs always add the fixed limitations-and-risks and ownership paragraphs.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "DisclosureFacts".
 */
export interface DisclosureFacts {
  /**
   * A school or company administrator can see the use (Edu/Enterprise plans).
   */
  admin_visibility: boolean;
  cost: CostKind;
  /**
   * Under 18 needs a parent's or guardian's permission.
   */
  guardian_permission: boolean;
  /**
   * Where data is processed (ISO country code), if known.
   */
  location?: string | null;
  min_age?: number | null;
  on_device: boolean;
  recipient: Recipient;
  retention: RetentionFact;
  sends: SentData[];
  training: TrainingFact;
  /**
   * A hash of all the facts and of the fixed paragraphs' wording: any change asks again.
   */
  version: number;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "Recipient".
 */
export interface Recipient {
  name: string;
  terms_url?: string | null;
}
/**
 * Everything the AI settings page shows (no network call).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "AiStatus".
 */
export interface AiStatus {
  /**
   * In priority order.
   */
  backends: AiBackendStatus[];
  budget: BudgetStatus;
  features: FeatureRouting[];
  providers: ModelProviderRecord[];
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "BudgetStatus".
 */
export interface BudgetStatus {
  /**
   * The monthly soft cap for API keys (`None`: no cap).
   */
  monthly_micro_usd?: number | null;
  /**
   * Estimated spend this month.
   */
  spent_micro_usd: number;
  /**
   * Warn from this share of the cap.
   */
  warn_at_percent: number;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "FeatureRouting".
 */
export interface FeatureRouting {
  choice?: ModelChoice | null;
  feature: AiFeature;
}
/**
 * The model a feature uses.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "ModelChoice".
 */
export interface ModelChoice {
  backend: BackendRef;
  effort: Effort;
  model: string;
}
/**
 * A provider the student added (the key itself stays in the keychain).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "ModelProviderRecord".
 */
export interface ModelProviderRecord {
  base_url: string;
  created_at: string;
  /**
   * The key's last 4 characters, for display.
   */
  key_last4?: string | null;
  label: string;
  on_device: boolean;
  preset: string;
  provider_id: string;
  wire: ProviderWire;
}
/**
 * Error returned by every facade method. Serialised as-is by the Tauri commands.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "AppError".
 */
export interface AppError {
  /**
   * Why a model call was refused (kind `blocked`).
   */
  blocked?: BlockReason | null;
  kind: AppErrorKind;
  /**
   * User-presentable; never contains a secret.
   */
  message: string;
  /**
   * Why a model call failed (kind `model`).
   */
  model_error?: ModelErrorKind | null;
  /**
   * How long the provider asked to wait before trying again.
   */
  retry_after_secs?: number | null;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "AppStatus".
 */
export interface AppStatus {
  counts: StoreCounts;
  data_dir: string;
  db_path: string;
  /**
   * Most recent successful sync over all sources.
   */
  last_synced_at?: string | null;
  sources: SourceRecord[];
  /**
   * True while any process holds `sync.lock`.
   */
  sync_in_progress: boolean;
  /**
   * Version of this PageLamp build.
   */
  version: string;
}
/**
 * Row counts for status screens / `sync_status`.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "StoreCounts".
 */
export interface StoreCounts {
  chunks: number;
  /**
   * Visible (not hidden) courses.
   */
  courses: number;
  events: number;
  hidden_courses: number;
  /**
   * Materials with text_status = ok and at least one chunk.
   */
  indexed_materials: number;
  materials: number;
  modules: number;
  /**
   * Courses under "Removed courses" (their tombstones), not counted above.
   */
  removed_courses: number;
  study_plans: number;
}
/**
 * A configured data source. Secrets (Canvas token, calendar-feed URL) are NOT stored here;
 * they live in the OS keychain keyed by `id` (see `secrets`).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "SourceRecord".
 */
export interface SourceRecord {
  /**
   * Non-secret configuration. Canvas: `{"base_url": "https://lms.example.edu"}`.
   * Folder: `{"path": "/Users/me/Courses", "term_start": "2026-09-08"?}`.
   * Ical: `{}` (the URL itself is a secret).
   */
  config: {
    [k: string]: unknown;
  };
  /**
   * e.g. `canvas:lms.example.edu`, `folder:3f2a…`, `ical:9b1c…`
   */
  id: string;
  kind: SourceKind;
  /**
   * Human label shown in status output, e.g. "Quercus" or "~/Courses".
   */
  label: string;
  /**
   * Error message of the most recent failed sync, cleared on success. Never contains secrets.
   */
  last_error?: string | null;
  /**
   * Machine-readable class of `last_error` (UIs branch on this, never on the message).
   */
  last_error_kind?: SourceErrorKind | null;
  last_synced_at?: string | null;
}
/**
 * Token counts of a run.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "TokenUsage".
 */
export interface TokenUsage {
  cached_input_tokens: number;
  /**
   * All input tokens, cached ones included.
   */
  input_tokens: number;
  /**
   * All output tokens, reasoning included.
   */
  output_tokens: number;
  /**
   * Of `output_tokens`, the ones spent thinking, if the provider says.
   */
  reasoning_tokens?: number | null;
}
/**
 * How one course of "Read syllabi for N courses" ended.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CalendarRunOutcome".
 */
export interface CalendarRunOutcome {
  /**
   * The gate stopped this course (each course is gated on its own).
   */
  blocked?: BlockReason | null;
  course_id: string;
  /**
   * The run failed, or was stopped (`cancelled`).
   */
  error?: AppErrorKind | null;
  /**
   * The proposal has no conflicts and isn't low quality (`accept_passing_proposals`).
   */
  passing: boolean;
  /**
   * The proposal the run made; `None` when it was blocked, failed, stopped or found no dates.
   */
  proposal_id?: number | null;
}
/**
 * A material a syllabus reading would use, and whether it does.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CalendarCandidate".
 */
export interface CalendarCandidate {
  /**
   * A file not downloaded yet that can be ("Download (counts as viewing in Canvas)").
   */
  downloadable: boolean;
  has_text: boolean;
  /**
   * Read by the scan and the AI (after the student's own choice, if any).
   */
  included: boolean;
  kind: MaterialKind;
  left_out?: CandidateLeftOut | null;
  material_id: string;
  reason: CandidateReason;
  /**
   * The student's add (true) or remove (false), if they chose.
   */
  student_choice?: boolean | null;
  title: string;
  url?: string | null;
}
/**
 * A calendar proposed from the course's materials (scan, AI reading or the student's AI app).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CalendarProposal".
 */
export interface CalendarProposal {
  /**
   * Set for origins `ai` and `ai_app`.
   */
  ai_label?: AiLabel | null;
  calendar: CourseCalendar;
  /**
   * What accepting would change compared with the calendar in force.
   */
  changes: CalendarChange[];
  /**
   * Choices between two for the student (V5, V7, V8).
   */
  conflicts: CalendarConflict[];
  course_id: string;
  created_at: string;
  dates: ProposedDate[];
  /**
   * What the checks dropped, by reason.
   */
  dropped: DropCount[];
  /**
   * The `course_calendars` row; accept or dismiss by it.
   */
  id: number;
  /**
   * Many claims dropped, the week table dropped, or the stated term from another year.
   */
  low_quality: boolean;
  origin: CalendarOrigin;
  /**
   * No conflicts and not low quality: "accept all that pass" may take it.
   */
  passing: boolean;
  resulting_phase: CoursePhase;
  /**
   * Today's week once accepted.
   */
  resulting_week_today?: number | null;
  /**
   * Show the one-time question (b) reminder with this proposal (D37 option 2, D49).
   */
  sharing_reminder: boolean;
}
/**
 * "AI-generated · <backend> · <model> · <date>" for dates an AI read (from alpha.3).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "AiLabel".
 */
export interface AiLabel {
  backend_label: string;
  created_at: string;
  model: string;
}
/**
 * An accepted or proposed course calendar (built by core, stored as `calendar_json`).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CourseCalendar".
 */
export interface CourseCalendar {
  breaks: CalendarBreak[];
  exam_period?: DateSpan | null;
  /**
   * A fixed label only, never requirements (rule 4).
   */
  final_exam_on?: string | null;
  /**
   * One for a one-term course, two for a full-year course.
   */
  segments: TeachingSegment[];
  /**
   * Optional per-week rows from a schedule table.
   */
  weeks: CalendarWeek[];
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CalendarBreak".
 */
export interface CalendarBreak {
  kind: BreakKind;
  /**
   * Short label from the course material (material text, rule 8: never in structure
   * outputs such as MCP or `evidence`). At most 80 characters.
   */
  label: string;
  /**
   * True when the break counts in the week numbering.
   */
  numbered: boolean;
  span: DateSpan;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "DateSpan".
 */
export interface DateSpan {
  end: string;
  start: string;
}
/**
 * One stretch of teaching: one for a one-term course, two for a full-year course.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "TeachingSegment".
 */
export interface TeachingSegment {
  first_class: string;
  /**
   * The number of the segment's first week (0 is allowed: "Week 0").
   */
  first_week_number: number;
  /**
   * The last day of classes, when known.
   */
  last_class?: string | null;
}
/**
 * One row of a schedule table.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CalendarWeek".
 */
export interface CalendarWeek {
  number: number;
  starts_on: string;
  /**
   * Plain text from the course material (rule 8: material text), at most 120 characters.
   */
  topic?: string | null;
}
/**
 * One line of "what accepting would change": a code and its params (like `EvidenceItem`).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CalendarChange".
 */
export interface CalendarChange {
  code: ChangeCode;
  params: EvidenceParam[];
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "EvidenceParam".
 */
export interface EvidenceParam {
  key: string;
  value: string;
}
/**
 * "A choice between two": the options the student picks from.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CalendarConflict".
 */
export interface CalendarConflict {
  code: ConflictCode;
  kind: DateKind;
  options: AlternativeDate[];
  segment: number;
}
/**
 * Another reading of the same field (V9), or an option in a conflict. Flat: no nesting.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "AlternativeDate".
 */
export interface AlternativeDate {
  date: string;
  end?: string | null;
  evidence: DateEvidence[];
  /**
   * Material text (rule 8); empty for dates from PageLamp's own evidence.
   */
  label: string;
}
/**
 * Where a date's words are (design §4 `DateEvidence`). The quote is material text: shown to
 * the student only, never in structure outputs (§7.11).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "DateEvidence".
 */
export interface DateEvidence {
  /**
   * The date follows from other rows of a validated table, not from this row's words.
   */
  derived: boolean;
  locator?: string | null;
  material_id: string;
  quote?: string | null;
  title: string;
  url?: string | null;
}
/**
 * One date of a proposal, with its quotes and the other readings.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "ProposedDate".
 */
export interface ProposedDate {
  alternatives: AlternativeDate[];
  /**
   * For `break_span`.
   */
  break_kind?: BreakKind | null;
  date: string;
  end?: string | null;
  evidence: DateEvidence[];
  kind: DateKind;
  label: string;
  numbered?: boolean | null;
  /**
   * 0, or 1 for the second half of a full-year course.
   */
  segment: number;
  /**
   * For `week_start`.
   */
  week?: number | null;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "DropCount".
 */
export interface DropCount {
  count: number;
  reason: DropReason;
}
/**
 * "≈ $x" before Generate: an upper bound.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CostEstimate".
 */
export interface CostEstimate {
  input_tokens: number;
  max_output_tokens: number;
  /**
   * `None` when the model's price is unknown.
   */
  micro_usd_upper?: number | null;
  price_known: boolean;
  reasoning_allowance: number;
  repair_possible: boolean;
  /**
   * What would stop the run if started now (over budget, price not acknowledged, a course
   * answered "not allowed", …).
   */
  would_block?: BlockReason | null;
}
/**
 * Everything the Timeline tab shows about a course's calendar.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CourseCalendarView".
 */
export interface CourseCalendarView {
  /**
   * The calendar in force, if the student accepted or typed one.
   */
  accepted?: AcceptedCalendar | null;
  /**
   * Why AI reading can't run for this course now.
   */
  blocked?: BlockReason | null;
  /**
   * The materials a reading would use, and why (read first, then by score).
   */
  candidates: CalendarCandidate[];
  course_id: string;
  /**
   * Pending proposals, at most one per origin.
   */
  proposals: CalendarProposal[];
  status: CalendarStatus;
}
/**
 * The calendar in force for a course, with where its dates came from.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "AcceptedCalendar".
 */
export interface AcceptedCalendar {
  accepted_at: string;
  ai_label?: AiLabel | null;
  calendar: CourseCalendar;
  /**
   * Ids of the quoted materials that changed.
   */
  changed_materials: string[];
  /**
   * The dates with their quotes (empty for the student's own dates).
   */
  dates: ProposedDate[];
  id: number;
  origin: CalendarOrigin;
  /**
   * A quoted material changed and a quote is no longer in it (§7.8). Still in force.
   */
  stale: boolean;
  /**
   * When the first such change was seen.
   */
  stale_since?: string | null;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CourseDatesInput".
 */
export interface CourseDatesInput {
  breaks: BreakInput[];
  exams_end?: string | null;
  first_class?: string | null;
  last_class?: string | null;
  /**
   * The second half of a full-year course.
   */
  second_segment?: SegmentInput | null;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "BreakInput".
 */
export interface BreakInput {
  end: string;
  kind: BreakKind;
  /**
   * Shown to the student only (never over MCP); at most 80 characters.
   */
  label?: string | null;
  /**
   * The break counts in the week numbering.
   */
  numbered: boolean;
  start: string;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "SegmentInput".
 */
export interface SegmentInput {
  first_class: string;
  last_class?: string | null;
  /**
   * True: this segment's first week is week 1; false: numbering continues.
   */
  restart_numbering: boolean;
}
/**
 * Everything needed to answer "what's going on in this course right now".
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CourseOverview".
 */
export interface CourseOverview {
  /**
   * Whether an AI app may read a course's material TEXT over MCP (docs/ARCHITECTURE.md §3
   * rule 8). Computed from `Course.ai_policy` and `Course.ai_access`, never stored.
   * Structure (titles, kinds, dates, weeks, URLs, counts), deadlines and study plans are
   * always available; only material text is withheld.
   */
  ai_materials: "readable" | "turned_off" | "withheld_by_policy";
  course: Course;
  current_modules: Module[];
  /**
   * Files a "download this course's files" action would fetch: kind `file`, text status
   * `not_downloaded` and no `download_blocked` reason (all weeks).
   */
  downloadable_files: number;
  last_synced_at?: string | null;
  lifecycle: CourseLifecycle;
  /**
   * Announcements posted in the last `RECENT_DAYS` days, newest first (titles + ids only).
   */
  recent_announcements: MaterialView[];
  /**
   * Materials published in the last `RECENT_DAYS` days, newest first (announcements excluded).
   */
  recent_materials: MaterialView[];
  source_label: string;
  timeline: CourseTimeline;
  /**
   * Deadlines due in the next `UPCOMING_DAYS` days, soonest first.
   */
  upcoming_deadlines: Deadline[];
}
/**
 * A course as read back from the store: synced fields + user overrides resolved.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "Course".
 */
export interface Course {
  /**
   * The student's switch "Let my AI app read this course's materials" (default on).
   * Use `ai_materials()` for the effective state — a `prohibited` policy wins over it.
   */
  ai_access: boolean;
  ai_policy: AiPolicy;
  /**
   * Free text the student recorded about the policy (e.g. a quote from the syllabus).
   */
  ai_policy_note?: string | null;
  code?: string | null;
  /**
   * False when the LMS no longer lists the course as active (e.g. the term ended). Such
   * courses are kept with all their data; only the student removes them.
   */
  enrollment_active: boolean;
  external_id: string;
  hidden: boolean;
  id: string;
  /**
   * The student's answer to "May this course's materials be shared with an AI service?"
   * (question (b)). Only `not_allowed` keeps material text from cloud models PageLamp runs
   * itself; the student's own AI app over MCP is unaffected.
   */
  material_sharing: "unanswered" | "allowed" | "not_sure" | "not_allowed";
  name: string;
  source_id: string;
  term_end?: string | null;
  /**
   * Where the effective term dates come from (`set_course_term(None, None)` clears the
   * user override and falls back to the synced dates).
   */
  term_source: "user" | "synced" | "none";
  /**
   * Effective term start = user override if set, else synced value.
   */
  term_start?: string | null;
  updated_at: string;
  url?: string | null;
}
/**
 * A unit of course structure (Canvas module, or a sub-folder like "Week 3").
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "Module".
 */
export interface Module {
  course_id: string;
  id: string;
  name: string;
  position?: number | null;
  unlock_at?: string | null;
  /**
   * Week number parsed from the name ("Week 3", "W03"), if any.
   */
  week_hint?: number | null;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CourseLifecycle".
 */
export interface CourseLifecycle {
  confidence: Confidence;
  evidence_items: EvidenceItem[];
  group: CourseGroup;
  /**
   * "I'm still taking this" until this date, when set.
   */
  kept_current_until?: string | null;
  /**
   * The latest material, announcement, event or module unlock date on or before today.
   */
  last_activity?: string | null;
  /**
   * The earliest course event (any kind but "other") from today to today + 30 days.
   */
  next_event?: string | null;
  /**
   * Since when the state holds, when known (e.g. the day an Ended course ended).
   */
  since?: string | null;
  /**
   * When classes start (Upcoming courses: "Starts Jan 11"), when known.
   */
  starts_on?: string | null;
  state: LifecycleState;
  /**
   * Ended or Inactive, and the suggestion isn't snoozed. Hidden courses are suggested too.
   */
  suggest_removal: boolean;
}
/**
 * One reason, as a code (an `EvidenceCode` value) and its parameters.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "EvidenceItem".
 */
export interface EvidenceItem {
  code: string;
  params: EvidenceParam[];
}
/**
 * A material as listed in views (no text; use `read_material` for text).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "MaterialView".
 */
export interface MaterialView {
  /**
   * Number of text chunks (pages/slides/sections) available via `read_material`.
   */
  chunk_count: number;
  course_id: string;
  /**
   * Why a `NotDownloaded` file cannot be downloaded on request (locked in the LMS, too
   * large); `None` when a download may work.
   */
  download_blocked?: DownloadBlock | null;
  id: string;
  kind: MaterialKind;
  module_id?: string | null;
  module_name?: string | null;
  published_at?: string | null;
  text_error?: string | null;
  /**
   * Why there is no text to read, in a word the app can show; `None` when the text is
   * there or was never tried (`pending`, `unsupported`, `not_downloaded`).
   */
  text_problem?: TextProblem | null;
  text_status: TextStatus;
  title: string;
  /**
   * Where the student can open the original (LMS URL or `file://` URL).
   */
  url?: string | null;
  week_hint?: number | null;
}
/**
 * "Where is this course right now", with the evidence that led to the conclusion so an AI
 * client can explain (and a student can correct) it.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CourseTimeline".
 */
export interface CourseTimeline {
  as_of: string;
  /**
   * During a break that doesn't count in the numbering: the last teaching week before it.
   */
  break_after_week?: number | null;
  calendar: CalendarStatus;
  /**
   * Confidence of `current_week` (Low when it is None).
   */
  confidence: "high" | "medium" | "low";
  /**
   * During a break: its kind.
   */
  current_break_kind?: BreakKind | null;
  /**
   * Modules considered current (most recently unlocked / matching current week).
   */
  current_module_ids: string[];
  current_week?: number | null;
  /**
   * The week features and `week_materials` use by default: the current teaching week, the
   * week before an unnumbered break, None in the exam period and outside the term.
   */
  default_week?: number | null;
  /**
   * Human-readable reasons, e.g. "module 'Week 4: Backprop' unlocked 2026-09-29". English,
   * for MCP and the CLI; UIs translate `evidence_items`. Never contains break labels, week
   * topics or quotes.
   */
  evidence: string[];
  evidence_items: EvidenceItem[];
  /**
   * During the exam period: the last teaching week ("Exams (after week 12)").
   */
  last_teaching_week?: number | null;
  /**
   * How far the professor's (non-bulk) week-numbered materials have got.
   */
  notes_week?: number | null;
  /**
   * True when the phase is `not_started` or `ended` (the exam period is not outside).
   */
  outside_term: boolean;
  phase: CoursePhase;
  phase_confidence: Confidence;
  /**
   * The day teaching starts, when known (a weekend first class → the next Monday), for
   * "Starts Jan 11"; surfaces show this instead of computing it.
   */
  starts_on?: string | null;
  term: TermResolution;
}
/**
 * The dates that count the weeks, and the dates that were not used.
 */
export interface TermResolution {
  /**
   * Set when the accepted calendar came from an AI (from alpha.3).
   */
  ai_label?: AiLabel | null;
  anchor: TermAnchorSource;
  /**
   * Low when `anchor` is `NoAnchor`.
   */
  anchor_confidence: "high" | "medium" | "low";
  /**
   * For `StudentConfirmed`: where the student's dates came from.
   */
  anchor_origin?: CalendarOrigin | null;
  breaks: CalendarBreak[];
  exams_end?: string | null;
  not_used: RejectedDates[];
  /**
   * Bounds the course lies within: the LMS term (plausible or not) ∪ the session window.
   * Never used to count weeks.
   */
  outer_frame?: DateSpan | null;
  student_end?: string | null;
  /**
   * The student's own first/last day of classes as saved (the raw overrides, whichever
   * are set). The dates form prefills from `teaching` and sends these back unchanged for
   * the fields the student didn't edit.
   */
  student_start?: string | null;
  teaching: TeachingSegment[];
  /**
   * Monday of teaching week 1 (weeks run Monday to Sunday).
   */
  week_one_monday?: string | null;
}
/**
 * Dates a source offered that were not used, and why.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "RejectedDates".
 */
export interface RejectedDates {
  end?: string | null;
  /**
   * True when only the end was not used (the start still counts weeks).
   */
  end_only: boolean;
  reason: RejectReason;
  source: TermAnchorSource;
  start?: string | null;
}
/**
 * A deadline/event enriched with its course's code and name (all `Event` fields are
 * flattened into the same JSON object).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "Deadline".
 */
export interface Deadline {
  course_code?: string | null;
  course_id?: string | null;
  course_name?: string | null;
  due_at?: string | null;
  ends_at?: string | null;
  id: string;
  kind: EventKind;
  source_id: string;
  starts_at?: string | null;
  title: string;
  updated_at: string;
  url?: string | null;
}
/**
 * One row of the course list ("where is each course this week").
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CourseSummary".
 */
export interface CourseSummary {
  /**
   * Whether an AI app may read a course's material TEXT over MCP (docs/ARCHITECTURE.md §3
   * rule 8). Computed from `Course.ai_policy` and `Course.ai_access`, never stored.
   * Structure (titles, kinds, dates, weeks, URLs, counts), deadlines and study plans are
   * always available; only material text is withheld.
   */
  ai_materials: "readable" | "turned_off" | "withheld_by_policy";
  counts: CourseCounts;
  course: Course;
  /**
   * When that source last synced successfully (data freshness).
   */
  last_synced_at?: string | null;
  lifecycle: CourseLifecycle1;
  next_deadline?: Deadline | null;
  /**
   * Label of the source this course came from (e.g. "Quercus", "~/Courses").
   */
  source_label: string;
  timeline: CourseTimeline;
}
/**
 * Per-course counts shown in course lists.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CourseCounts".
 */
export interface CourseCounts {
  /**
   * Materials whose text the student's AI app can read: indexed materials, but 0 unless
   * the course's `ai_materials` state is `readable`.
   */
  indexed_materials: number;
  materials: number;
  modules: number;
  /**
   * Deadlines due in the next `UPCOMING_DAYS` days.
   */
  upcoming_deadlines: number;
}
/**
 * Upcoming / current / finishing / ended, the Past group and removal suggestions.
 */
export interface CourseLifecycle1 {
  confidence: Confidence;
  evidence_items: EvidenceItem[];
  group: CourseGroup;
  /**
   * "I'm still taking this" until this date, when set.
   */
  kept_current_until?: string | null;
  /**
   * The latest material, announcement, event or module unlock date on or before today.
   */
  last_activity?: string | null;
  /**
   * The earliest course event (any kind but "other") from today to today + 30 days.
   */
  next_event?: string | null;
  /**
   * Since when the state holds, when known (e.g. the day an Ended course ended).
   */
  since?: string | null;
  /**
   * When classes start (Upcoming courses: "Starts Jan 11"), when known.
   */
  starts_on?: string | null;
  state: LifecycleState;
  /**
   * Ended or Inactive, and the suggestion isn't snoozed. Hidden courses are suggested too.
   */
  suggest_removal: boolean;
}
/**
 * What one sync did for one course (the `pagelamp sync` summary; desktop status screens).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CourseSyncSummary".
 */
export interface CourseSyncSummary {
  /**
   * Course code, or name when it has no code.
   */
  course: string;
  /**
   * Deadlines/events read for this course.
   */
  events: number;
  /**
   * Files listed (downloaded or not).
   */
  files: number;
  modules: number;
  pages: number;
  warnings: number;
}
/**
 * The most recent crash (`logs/last-crash.json`), until cleared.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CrashReport".
 */
export interface CrashReport {
  /**
   * `file.rs:line:column` of the panic.
   */
  location?: string | null;
  /**
   * Redacted, at most 500 characters.
   */
  message: string;
  process: ProcessKind;
  time: string;
  version: string;
}
/**
 * `pagelamp doctor`: the facts a maintainer needs to help, and nothing personal.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "DoctorReport".
 */
export interface DoctorReport {
  ai?: AiDoctor;
  arch: string;
  courses: number;
  /**
   * With the home directory shortened to `~`.
   */
  data_dir: string;
  /**
   * Why the database could not be read (then the counts are 0).
   */
  database_error?: string | null;
  /**
   * Courses whose LMS term looks like an enrollment window, so it isn't used to count weeks
   * (calendar design §6.3). A count, never names.
   */
  enrollment_window_terms?: number;
  events: number;
  extract_worker: ExtractWorkerCheck;
  hidden_courses: number;
  keychain_available: boolean;
  keychain_error?: string | null;
  last_crash?: CrashReport | null;
  logs_dir: string;
  materials: number;
  mcp_clients: McpClientPresence;
  os: string;
  /**
   * Removed courses still waiting: for their purge (the undo window) or for their downloaded
   * files to go to the Trash (calendar design §8.3). A count, never names.
   */
  removals_waiting?: number;
  schema_version?: number | null;
  sources: DoctorSource[];
  /**
   * Files the extraction worker could not read, per reason (reasons without files left
   * out; empty when the database can't be read).
   */
  unreadable_files: UnreadableFiles[];
  version: string;
}
/**
 * Models PageLamp calls itself: keys present (never the keys), local servers running.
 */
export interface AiDoctor {
  /**
   * Ollama and LM Studio at their usual addresses on this computer.
   */
  local_servers: LocalServer[];
  /**
   * The providers the student added.
   */
  providers: AiProviderCheck[];
}
/**
 * A local model server found on this computer.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "LocalServer".
 */
export interface LocalServer {
  base_url: string;
  kind: LocalServerKind;
  running: boolean;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "AiProviderCheck".
 */
export interface AiProviderCheck {
  /**
   * Whether its key is in the keychain (`None`: it needs none).
   */
  key_present?: boolean | null;
  on_device: boolean;
  /**
   * The kind of provider (`openai`, `ollama`, `custom`, …).
   */
  preset: string;
  /**
   * On this computer: whether its server accepts connections (`None`: not on this
   * computer, so not contacted).
   */
  reachable?: boolean | null;
}
/**
 * `doctor`'s check of the extraction worker: it is started once.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "ExtractWorkerCheck".
 */
export interface ExtractWorkerCheck {
  /**
   * How long starting it and getting its answer took (`ok` only).
   */
  spawn_ms?: number | null;
  status: ExtractWorkerStatus;
}
/**
 * Whether each AI app's config has a PageLamp entry (presence only; nothing else is read
 * out of those files).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "McpClientPresence".
 */
export interface McpClientPresence {
  claude_code: boolean;
  claude_desktop: boolean;
  codex: boolean;
}
/**
 * A source as `doctor` shows it: no ids, URLs or labels.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "DoctorSource".
 */
export interface DoctorSource {
  kind: SourceKind;
  last_error_kind?: SourceErrorKind | null;
  last_synced_at?: string | null;
  /**
   * The last sync succeeded (false when it failed or never ran).
   */
  ok: boolean;
}
/**
 * How many files the extraction worker could not read for one reason.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "UnreadableFiles".
 */
export interface UnreadableFiles {
  count: number;
  kind: TextErrorKind;
}
/**
 * Provenance of every generated result (the "AI-generated · backend · model · date" label).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "GenerationMeta".
 */
export interface GenerationMeta {
  backend_label: string;
  context: ContextSummary;
  created_at: string;
  est_cost_micro_usd?: number | null;
  /**
   * Counts are estimates (the run was cancelled before the provider reported them).
   */
  estimated: boolean;
  feature: AiFeature;
  generation_id: string;
  model: string;
  prompt_version: number;
  usage: TokenUsage;
}
/**
 * What a context contains, for the UI (no text).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "ContextSummary".
 */
export interface ContextSummary {
  courses: ContextCourse[];
  /**
   * Materials left out, and why.
   */
  left_out: LeftOutMaterial[];
  /**
   * Materials whose text was included.
   */
  materials_included: number;
  /**
   * Materials whose text was cut to fit the budget.
   */
  materials_trimmed: number;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "ContextCourse".
 */
export interface ContextCourse {
  course_id: string;
  state: AiMaterialsState;
  /**
   * Whether any material text of this course is in the context (else structure only).
   */
  text_included: boolean;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "LeftOutMaterial".
 */
export interface LeftOutMaterial {
  material_id: string;
  reason: LeftOutReason;
  title: string;
}
/**
 * Every course's lifecycle, and whether the Courses page shows "N courses look finished".
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "LifecycleSummary".
 */
export interface LifecycleSummary {
  /**
   * Until when "Not now" on the banner holds, if it was pressed and hasn't expired.
   */
  banner_snoozed_until?: string | null;
  /**
   * Every course, hidden ones included (hidden past courses are most of the backlog).
   */
  courses: CourseLifecycleEntry[];
  /**
   * True when some suggested course is not covered by a snoozed banner.
   */
  show_banner: boolean;
  /**
   * Ids of the courses suggested for removal (`lifecycle.suggest_removal`).
   */
  suggested: string[];
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CourseLifecycleEntry".
 */
export interface CourseLifecycleEntry {
  code?: string | null;
  course_id: string;
  hidden: boolean;
  lifecycle: CourseLifecycle;
  name: string;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "McpClientConfig".
 */
export interface McpClientConfig {
  client: McpClient;
  /**
   * Where the snippet goes, e.g. "~/Library/Application Support/Claude/claude_desktop_config.json".
   */
  config_path_hint?: string | null;
  /**
   * The snippet / command to copy.
   */
  content: string;
  install_kind: InstallKind;
  launch: McpLaunch;
  /**
   * Machine-readable code of each entry of `notes` (same length, same order) so UIs can
   * localise.
   */
  note_codes: McpNoteCode[];
  /**
   * Facts the student should know (plan availability, restart the app, …), in English.
   */
  notes: string[];
  /**
   * e.g. "Claude Desktop".
   */
  title: string;
}
/**
 * How an MCP client launches the server — the single source every snippet (and, later,
 * a `.mcpb` Desktop Extension manifest) is generated from.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "McpLaunch".
 */
export interface McpLaunch {
  args: string[];
  /**
   * Absolute path of the `pagelamp` binary.
   */
  command: string;
  /**
   * Extra environment (only `PAGELAMP_HOME` when the data dir is not the default).
   */
  env: {
    [k: string]: string;
  };
  /**
   * Set when `command` lives somewhere it won't be found later; every config then starts
   * with a `RunFromTemporaryLocation` note.
   */
  temporary_location?: TemporaryLocation | null;
}
/**
 * A model a backend offers.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "ModelInfo".
 */
export interface ModelInfo {
  context_window?: number | null;
  id: string;
  label?: string | null;
  on_device: boolean;
  /**
   * Its price is in PageLamp's price list (else the budget can't be enforced for it).
   */
  price_known: boolean;
  /**
   * Thinking can't be turned off ("lowest" still thinks, and costs more).
   */
  reasoning_always_on: boolean;
  /**
   * Served by a local app but run in the cloud (Ollama cloud models).
   */
  runs_in_cloud: boolean;
  /**
   * Features this release suggests the model for.
   */
  suggested_for: AiFeature[];
}
/**
 * What "Test" found out.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "ProbeReport".
 */
export interface ProbeReport {
  error?: ModelErrorKind | null;
  latency_ms: number;
  ok: boolean;
  structured_output_tier?: StructuredOutputTier | null;
  thinking_always_on: boolean;
}
/**
 * A provider PageLamp can set up.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "ProviderPreset".
 */
export interface ProviderPreset {
  base_url_editable: boolean;
  data_policy: DisclosureFacts1;
  default_base_url?: string | null;
  id: string;
  label: string;
  /**
   * Runs on this computer (Ollama, LM Studio).
   */
  local: boolean;
  needs_key: boolean;
  wire: ProviderWire;
}
/**
 * What a backend is told and what happens to it (Canvas §2E items): codes and plain values the
 * UIs render. The UIs always add the fixed limitations-and-risks and ownership paragraphs.
 */
export interface DisclosureFacts1 {
  /**
   * A school or company administrator can see the use (Edu/Enterprise plans).
   */
  admin_visibility: boolean;
  cost: CostKind;
  /**
   * Under 18 needs a parent's or guardian's permission.
   */
  guardian_permission: boolean;
  /**
   * Where data is processed (ISO country code), if known.
   */
  location?: string | null;
  min_age?: number | null;
  on_device: boolean;
  recipient: Recipient;
  retention: RetentionFact;
  sends: SentData[];
  training: TrainingFact;
  /**
   * A hash of all the facts and of the fixed paragraphs' wording: any change asks again.
   */
  version: number;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "PurgeReport".
 */
export interface PurgeReport {
  /**
   * A purged course asked for the pre-update backup to go, and it did.
   */
  backup_deleted: boolean;
  /**
   * Deleting the pre-update backup failed (the purge went ahead).
   */
  backup_failed: boolean;
  /**
   * `removed_id`s whose files couldn't be moved to the Trash (kept; retried later).
   */
  files_pending: string[];
  /**
   * `removed_id`s purged now.
   */
  purged: string[];
}
/**
 * Options of an AI reading run.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "ReadCalendarOptions".
 */
export interface ReadCalendarOptions {
  /**
   * The student chose to go over the monthly budget for this run.
   */
  override_budget: boolean;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "RemovalPreview".
 */
export interface RemovalPreview {
  backup?: BackupInfo | null;
  items: RemovalPreviewItem[];
}
/**
 * The pre-update backup (`pagelamp.db.v<N>.bak`) still holds the course's text.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "BackupInfo".
 */
export interface BackupInfo {
  age_days: number;
  /**
   * "Also delete the pre-update backup" is ticked by default when it is 14+ days old.
   */
  delete_by_default: boolean;
  /**
   * `backup_old` (safe to delete) or `backup_recent` (the way back from a bad update).
   */
  reason_code: string;
}
/**
 * One course in the removal dialog.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "RemovalPreviewItem".
 */
export interface RemovalPreviewItem {
  /**
   * The LMS restricts the course by date, so it can't be synced again.
   */
  cannot_sync_again: boolean;
  code?: string | null;
  course_id: string;
  /**
   * The student changed the course's settings (AI policy, access, dates…).
   */
  custom_settings: boolean;
  deadlines: number;
  downloaded_bytes: number;
  downloaded_files: number;
  generated_items: number;
  lifecycle: CourseLifecycle;
  lost_after_purge: LostAfterPurge[];
  materials: number;
  name: string;
  /**
   * A folder course: its files are never touched.
   */
  own_folder_untouched: boolean;
  source_kind: SourceKind;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "RemovalReport".
 */
export interface RemovalReport {
  /**
   * The pre-update backup was deleted now (`purge_now`; otherwise it goes with the purge).
   */
  backup_deleted: boolean;
  /**
   * Deleting the pre-update backup failed (the courses are removed all the same).
   */
  backup_failed: boolean;
  purged_now: boolean;
  removed: RemovedCourse[];
}
/**
 * A course in "Removed courses".
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "RemovedCourse".
 */
export interface RemovedCourse {
  code?: string | null;
  course_id: string;
  external_id: string;
  /**
   * Moving the downloaded files to the Trash failed; retried later.
   */
  files_pending: boolean;
  keep_files: boolean;
  name: string;
  /**
   * When the local data will be deleted (pending only).
   */
  purge_after?: string | null;
  /**
   * Whole days until the purge ("deleted in 3 days"); None once purged.
   */
  purge_in_days?: number | null;
  purged_at?: string | null;
  reason: RemovalReason;
  removed_at: string;
  /**
   * What `restore_course` / `forget_removed_course` take.
   */
  removed_id: string;
  source_id: string;
  source_kind: SourceKind;
  state: TombstoneState;
}
/**
 * What "Remove all AI data" removed.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "RemoveAiDataReport".
 */
export interface RemoveAiDataReport {
  /**
   * The pre-update database backup was deleted too (it holds AI data from schema 4 on).
   */
  backup_removed: boolean;
  generations_removed: number;
  providers_removed: number;
  usage_rows_removed: number;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "RemoveOptions".
 */
export interface RemoveOptions {
  /**
   * Delete the pre-update backup with the purge (at once with `purge_now`); an undo keeps it.
   */
  delete_pre_update_backup: boolean;
  keep_downloaded_files: boolean;
  /**
   * Delete at once instead of in 7 days (no undo).
   */
  purge_now: boolean;
  /**
   * None: from each course's lifecycle (Ended → ended, Inactive → inactive, else other).
   */
  reason?: RemovalReason | null;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "RestoreOutcome".
 */
export interface RestoreOutcome {
  course_id?: string | null;
  failure?: RestoreFailure | null;
  restored: boolean;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "SearchHit".
 */
export interface SearchHit {
  chunk_ord: number;
  course_code?: string | null;
  course_id: string;
  locator?: string | null;
  material_id: string;
  material_title: string;
  /**
   * Lower is better (FTS5 bm25).
   */
  score: number;
  /**
   * Short excerpt around the match (FTS5 snippet), with matches wrapped in «».
   */
  snippet: string;
  url?: string | null;
  week_hint?: number | null;
}
/**
 * Outcome of syncing one source. A failing source is `ok: false` (not an `Err`), so
 * `sync_all` can report partial success.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "SourceSyncResult".
 */
export interface SourceSyncResult {
  /**
   * Per-course details (Canvas; empty for other sources).
   */
  course_summaries: CourseSyncSummary[];
  courses: number;
  error?: string | null;
  error_kind?: SourceErrorKind | null;
  events: number;
  files_downloaded: number;
  files_indexed: number;
  finished_at: string;
  kind: SourceKind;
  label: string;
  materials: number;
  modules: number;
  ok: boolean;
  /**
   * HTTP requests made (Canvas; None for other sources).
   */
  requests?: number | null;
  source_id: string;
  started_at: string;
  warnings: string[];
}
/**
 * What the app should do now (M0 subset; `startup_tasks`).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "StartupTasks".
 */
export interface StartupTasks {
  /**
   * Run the automatic update check now: it is on, the student saw the disclosure (onboarding
   * or What's new), no What's new is waiting, and the last check is 24 h or more ago.
   */
  update_check_due: boolean;
  /**
   * The version this launch updated from (`None`: not an update, or an update from 0.1).
   * Shows the "quit and reopen your AI app" banner.
   */
  updated_from?: string | null;
  /**
   * Show What's new (upgraders only) until `acknowledge_whats_new`.
   */
  whats_new?: WhatsNew | null;
}
/**
 * What's new since `since` (`None`: an update from 0.1, which didn't record its version).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "WhatsNew".
 */
export interface WhatsNew {
  since?: string | null;
  topics: WhatsNewTopic[];
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "StoredStudyPlan".
 */
export interface StoredStudyPlan {
  created_at: string;
  id: number;
  plan: StudyPlan;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "StudyPlan".
 */
export interface StudyPlan {
  horizon_end: string;
  horizon_start: string;
  items: StudyPlanItem[];
  notes?: string | null;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "StudyPlanItem".
 */
export interface StudyPlanItem {
  /**
   * Course id (or code) this task belongs to, if any.
   */
  course_id?: string | null;
  date: string;
  description?: string | null;
  done?: boolean;
  /**
   * Materials to study for this item (ids from `week_materials` / `search_materials`).
   */
  material_ids?: string[];
  minutes?: number | null;
  title: string;
}
/**
 * A course "Read syllabi for N courses" would read (the facade decides which).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "SyllabusOffer".
 */
export interface SyllabusOffer {
  /**
   * How many candidate materials it has.
   */
  candidates: number;
  course_id: string;
  /**
   * Some candidate has text to read.
   */
  has_text: boolean;
  /**
   * Why it is offered: `no_calendar`.
   */
  reason_code: string;
}
/**
 * Options for a sync run. All fields have defaults, so `{}` is a valid request.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "SyncRequest".
 */
export interface SyncRequest {
  /**
   * Download LMS (Canvas) files and index their text. Default FALSE: downloading a file
   * through Canvas counts as viewing it (it can complete "must view" module requirements
   * and shows up in instructor analytics), so files are listed as `not_downloaded` unless
   * the student explicitly asks — see `App::download_course_files`. Folder sources are
   * local and always indexed.
   */
  download_files?: boolean;
  /**
   * Skip LMS files larger than this many megabytes.
   */
  max_file_mb?: number;
  /**
   * Only sync these courses (ids or codes); empty = all.
   */
  only_courses?: string[];
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "SyncSummary".
 */
export interface SyncSummary {
  finished_at: string;
  /**
   * True when every source synced successfully.
   */
  ok: boolean;
  results: SourceSyncResult[];
  started_at: string;
}
/**
 * One update check and how it ended (`record_update_check`).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "UpdateCheckRecord".
 */
export interface UpdateCheckRecord {
  at: string;
  channel: UpdateChannel;
  outcome: UpdateCheckOutcome;
}
/**
 * The student's update settings.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "UpdatePrefs".
 */
export interface UpdatePrefs {
  /**
   * Check for updates automatically (daily). Default on (D2).
   */
  auto_check: boolean;
  /**
   * The chosen channel; `None` = the default for this build (`effective_update_channel`).
   */
  channel?: UpdateChannel | null;
}
/**
 * One backend × model × feature of a month.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "UsageRow".
 */
export interface UsageRow {
  backend_label: string;
  cost_basis: CostBasis;
  /**
   * Some counts are PageLamp's estimates (cancelled runs).
   */
  estimated: boolean;
  feature: AiFeature;
  /**
   * All input tokens, cached ones included.
   */
  input_tokens: number;
  /**
   * Estimated cost: set for `priced` (and 0 for `free_on_device`), null for `unpriced` and
   * `plan`.
   */
  micro_usd?: number | null;
  model: string;
  /**
   * All output tokens, reasoning included.
   */
  output_tokens: number;
  /**
   * Of `output_tokens`, the ones spent thinking (0 when the provider doesn't say).
   */
  reasoning_tokens: number;
  runs: number;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "UsageSummary".
 */
export interface UsageSummary {
  budget: BudgetStatus;
  /**
   * The first day of the month.
   */
  month: string;
  rows: UsageRow[];
  /**
   * The priced rows' total (what the budget counts).
   */
  total_micro_usd: number;
}
/**
 * Materials of one teaching week.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "WeekMaterials".
 */
export interface WeekMaterials {
  /**
   * Whether an AI app may read a course's material TEXT over MCP (docs/ARCHITECTURE.md §3
   * rule 8). Computed from `Course.ai_policy` and `Course.ai_access`, never stored.
   * Structure (titles, kinds, dates, weeks, URLs, counts), deadlines and study plans are
   * always available; only material text is withheld.
   */
  ai_materials: "readable" | "turned_off" | "withheld_by_policy";
  /**
   * Every week that has at least one module or material (plus the current week), ascending —
   * drives the ‹ Week › switcher.
   */
  available_weeks: number[];
  course: Course;
  materials: MaterialView[];
  /**
   * Modules belonging to this week.
   */
  modules: Module[];
  /**
   * Explains any fallback, e.g. "current week unknown — showing materials of the last 14 days".
   */
  note?: string | null;
  /**
   * Machine-readable class of `note` (UIs localise from this; `note` stays English).
   */
  note_kind?: WeekNoteKind | null;
  /**
   * The week the caller asked for (None = "current week").
   */
  requested_week?: number | null;
  timeline: CourseTimeline;
  /**
   * The week actually shown (None when no week could be determined; see `note`).
   */
  week?: number | null;
}
/**
 * `doctor`'s AI facts (M1): whether keys are there — never a key — and whether the model
 * servers on this computer answer. No provider address or id: doctor output is shared in
 * issues, and an address can name a school's server.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "AiDoctor".
 */
export interface AiDoctor1 {
  /**
   * Ollama and LM Studio at their usual addresses on this computer.
   */
  local_servers: LocalServer[];
  /**
   * The providers the student added.
   */
  providers: AiProviderCheck[];
}
/**
 * The dates that count the course's weeks, and the dates that were not used (design §3.3).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "TermResolution".
 */
export interface TermResolution1 {
  /**
   * Set when the accepted calendar came from an AI (from alpha.3).
   */
  ai_label?: AiLabel | null;
  anchor: TermAnchorSource;
  /**
   * Low when `anchor` is `NoAnchor`.
   */
  anchor_confidence: "high" | "medium" | "low";
  /**
   * For `StudentConfirmed`: where the student's dates came from.
   */
  anchor_origin?: CalendarOrigin | null;
  breaks: CalendarBreak[];
  exams_end?: string | null;
  not_used: RejectedDates[];
  /**
   * Bounds the course lies within: the LMS term (plausible or not) ∪ the session window.
   * Never used to count weeks.
   */
  outer_frame?: DateSpan | null;
  student_end?: string | null;
  /**
   * The student's own first/last day of classes as saved (the raw overrides, whichever
   * are set). The dates form prefills from `teaching` and sends these back unchanged for
   * the fields the student didn't edit.
   */
  student_start?: string | null;
  teaching: TeachingSegment[];
  /**
   * Monday of teaching week 1 (weeks run Monday to Sunday).
   */
  week_one_monday?: string | null;
}
